type Tier = "flag" | "watch" | "low";

interface SafetyItem {
  id: string;
  heading: string;
  tier: Tier;
  body: string;
  context: string;
}

const SAFETY_ITEMS: SafetyItem[] = [
  {
    id: "renal-toxicity",
    heading: "Renal toxicity",
    tier: "flag",
    body:
      "The pivotal primate study (Barnhart et al. 2011) documented significant nephrotoxicity concurrent with the weight loss results. Treated monkeys showed elevated serum creatinine, elevated BUN, and histopathological evidence of acute kidney injury. The mechanism is consistent with the peptide&apos;s mode of action: the pro-apoptotic KLAK sequence, nominally targeted to adipose vasculature via prohibitin, appears to also affect renal vasculature. Kidney damage partially reversed after treatment cessation but was not fully resolved in all animals within the observation window.",
    context:
      "This is not a speculative concern — it is an observed, mechanistically coherent toxicity signal in the only controlled study of adipotide in a higher mammal. Any human use carries unknown but real renal risk. No human renal monitoring protocol exists because no human trial has been conducted.",
  },
  {
    id: "no-human-safety-data",
    heading: "Zero human safety data",
    tier: "flag",
    body:
      "No phase I, phase II, or any other human clinical study of adipotide has been completed and published. There is no established safe human dose, no safe administration schedule, and no validated monitoring approach. Community use reports are not a substitute for clinical data — they are unmonitored experimentation with unknown compound purity and concentration.",
    context:
      "The absence of human data means that every aspect of the human safety profile is unknown: systemic half-life, volume of distribution, immunogenicity, off-target effects, renal dose-response, organ-specific toxicity. The primate study provides the only guidance, and it documented toxicity.",
  },
  {
    id: "vascular-apoptosis-offtarget",
    heading: "Off-target vascular apoptosis",
    tier: "watch",
    body:
      "The D[KLAKLAK]2 pro-apoptotic effector is a potent cell-death signal. Its targeting specificity depends entirely on the prohibitin-binding domain reaching only adipose vasculature. The primate study suggests this selectivity is imperfect. Other vascular beds expressing prohibitin — including renal, hepatic, or cardiac vasculature — could be affected at sufficient doses.",
    context:
      "The selectivity concern is dose-dependent. At lower doses the targeting may be more selective; at higher doses off-target vascular effects could occur. Without human dose-finding data, the safe dose window (if any exists) is unknown.",
  },
  {
    id: "research-chemical-quality",
    heading: "Research-chemical sourcing quality and sterility",
    tier: "watch",
    body:
      "Adipotide sourced from online research-chemical vendors is not pharmaceutical grade. Purity, correct peptide sequence, correct concentration, and sterility cannot be verified without independent lab testing. Injecting non-sterile compounds carries risks of infection, abscess, and systemic sepsis beyond the pharmacological risks of adipotide itself.",
    context:
      "Community sourcing reports show significant batch-to-batch variability for research peptides generally. There is no regulatory oversight of research-chemical peptide quality for human use.",
  },
];

const TIER_STYLE: Record<
  Tier,
  { bg: string; border: string; label: string; labelColor: string }
> = {
  flag: {
    bg: "rgba(158,56,0,0.07)",
    border: "rgba(158,56,0,0.20)",
    label: "Stop signal",
    labelColor: "#9e3800",
  },
  watch: {
    bg: "rgba(124,82,0,0.06)",
    border: "rgba(124,82,0,0.17)",
    label: "Worth watching",
    labelColor: "#7c5200",
  },
  low: {
    bg: "rgba(21,100,58,0.05)",
    border: "rgba(21,100,58,0.13)",
    label: "Low concern",
    labelColor: "#155e38",
  },
};

export default function AdipotideSafetyPanel() {
  return (
    <div className="reta-safety">
      <div className="reta-safety__context">
        Adipotide has a serious, unresolved renal toxicity signal from the only controlled
        higher-mammal study of the compound, and zero human safety data. This combination makes
        it one of the higher-risk research peptides in community circulation. The enthusiasm
        generated by the primate weight loss results should be understood alongside the nephrotoxicity
        data from the same study.
      </div>
      <div className="reta-safety__list">
        {SAFETY_ITEMS.map((item) => {
          const st = TIER_STYLE[item.tier];
          return (
            <div
              key={item.id}
              className="reta-safety__entry"
              style={{ background: st.bg, border: `1px solid ${st.border}` }}
            >
              <div className="reta-safety__entry-top">
                <div className="reta-safety__entry-heading">{item.heading}</div>
                <div
                  className="reta-safety__entry-tier"
                  style={{ color: st.labelColor, borderColor: st.border }}
                >
                  {st.label}
                </div>
              </div>
              <div className="reta-safety__entry-body">{item.body}</div>
              <div className="reta-safety__entry-context">{item.context}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
