import type { Metadata } from "next";
import { listPeptides, listBlends, listTopics } from "@/lib/content";
import HomeSearch from "@/components/HomeSearch";
import NavBar from "@/components/NavBar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const peptides = listPeptides();
  const blends = listBlends();
  const topics = listTopics();
return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar peptides={peptides} blends={blends} topics={topics} />

{children}
      </body>
    </html>
  );
}
