from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]   # repo root
SRC  = ROOT / "content" / "_index" / "search_routes_v1.json"
OUTD = ROOT / "app" / "web" / "lib" / "generated"
OUT  = OUTD / "search_routes_v1.ts"

def die(msg: str) -> None:
    raise SystemExit(f"FAIL: {msg}")

if not SRC.exists():
    die(f"missing source index: {SRC}")

data = json.loads(SRC.read_text(encoding="utf-8"))
terms = data.get("terms")
if not isinstance(terms, list):
    die("source index missing terms[] list")

OUTD.mkdir(parents=True, exist_ok=True)

# Keep it simple: export the whole JSON as a default object.
# This is deterministic + bundler-friendly (no FS reads at runtime).
payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

ts = (
    "/* AUTO-GENERATED. DO NOT EDIT.\n"
    "   Source: content/_index/search_routes_v1.json\n"
    "   Generated by: app/web/scripts/gen_search_routes.py */\n\n"
    "const SEARCH_ROUTES_V1 = "
    + payload
    + " as const;\n\n"
    "export default SEARCH_ROUTES_V1;\n"
)

OUT.write_text(ts, encoding="utf-8")
print(f"OK: wrote {OUT} (terms={len(terms)})")
