import Link from "next/link";
import { loadInteractionClassesV1, loadInteractionsIndexV1 } from "@/lib/content";

function norm(s: string) {
  return (s || "").trim().toLowerCase();
}

export default async function InteractionDetailPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ kind?: string }>;
}) {
  const { slug } = await params;
  const sp = await searchParams;
  const kind = sp?.kind === "supplement" ? "supplement" : "drug";

  const tax = loadInteractionClassesV1();
  const idx = loadInteractionsIndexV1();

  const classes = kind === "supplement" ? tax?.supplement_classes ?? [] : tax?.drug_classes ?? [];
  const hit = classes.find((c) => c.slug === slug);

  const byName = kind === "supplement" ? idx?.by_supplement_class_name ?? {} : idx?.by_drug_class_name ?? {};

  // Match terms by exact name keys (case-insensitive)
  const termSet = new Set<string>();
  if (hit?.title) termSet.add(norm(hit.title));
  (hit?.aka ?? []).forEach((a) => termSet.add(norm(a)));

  const slugs = new Set<string>();
  for (const [name, peptideSlugs] of Object.entries(byName)) {
    if (termSet.has(norm(name))) {
      peptideSlugs.forEach((s) => slugs.add(s));
    }
  }

  const list = Array.from(slugs).sort();

  return (
    <main style={{ maxWidth: 980, margin: "0 auto", padding: "24px 16px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
        <div>
          <div style={{ fontSize: 12, opacity: 0.75, fontWeight: 800 }}>
            <Link href="/interactions" style={{ textDecoration: "none" }}>Interactions</Link>
            {" "}→{" "}
            {kind === "supplement" ? "Supplement class" : "Medication class"}
          </div>
          <h1 style={{ fontSize: 24, fontWeight: 950, margin: "6px 0 0 0" }}>
            {hit?.title ?? slug}
          </h1>
        </div>

        <Link
          href="/safety/safety_interactions"
          style={{
            textDecoration: "none",
            fontWeight: 900,
            fontSize: 13,
            padding: "10px 12px",
            borderRadius: 999,
            border: "1px solid rgba(0,0,0,0.10)",
            background: "rgba(0,0,0,0.02)",
          }}
        >
          Safety overview
        </Link>
      </div>

      {hit?.notes ? (
        <div style={{ marginTop: 12, padding: 14, borderRadius: 16, border: "1px solid rgba(0,0,0,0.08)", background: "#fff" }}>
          <div style={{ fontSize: 13, opacity: 0.8, lineHeight: 1.5 }}>{hit.notes}</div>
        </div>
      ) : null}

      {Array.isArray(hit?.aka) && hit!.aka!.length ? (
        <div style={{ marginTop: 12, display: "flex", flexWrap: "wrap", gap: 8 }}>
          {hit!.aka!.map((a) => (
            <span key={a} style={{ fontSize: 12, fontWeight: 800, padding: "6px 10px", borderRadius: 999, border: "1px solid rgba(0,0,0,0.10)", background: "rgba(0,0,0,0.02)" }}>
              {a}
            </span>
          ))}
        </div>
      ) : null}

      <section style={{ marginTop: 18 }}>
        <h2 style={{ fontSize: 16, fontWeight: 900, margin: 0 }}>Peptides that mention this interaction class</h2>
        <p style={{ marginTop: 8, fontSize: 13, opacity: 0.8, lineHeight: 1.5 }}>
          This list is generated by scanning peptide pages for structured interaction entries. It reflects what has been populated so far.
        </p>

        {!list.length ? (
          <div style={{ marginTop: 12, padding: 14, borderRadius: 16, background: "rgba(0,0,0,0.03)", fontSize: 13, opacity: 0.85 }}>
            No peptides are currently indexed for this class.
          </div>
        ) : (
          <div style={{ marginTop: 10, display: "grid", gap: 10 }}>
            {list.map((s) => (
              <Link
                key={s}
                href={`/peptide/${s}`}
                style={{
                  textDecoration: "none",
                  color: "inherit",
                  border: "1px solid rgba(0,0,0,0.08)",
                  borderRadius: 16,
                  padding: 14,
                  background: "#fff",
                }}
              >
                <div style={{ fontWeight: 950 }}>{s}</div>
                <div style={{ marginTop: 6, fontSize: 12, opacity: 0.75 }}>Open peptide page</div>
              </Link>
            ))}
          </div>
        )}
      </section>
    </main>
  );
}
